name = "possums"
main = "worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "POSSUMS_KV"
id = "75431ab7f9b14976bea6e40776f4e081"
