name = "possums"
main = "worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "POSSUMS_KV"
id = "acb2c99567ac4e00834b4915ad9bd33a"
